# Utiliser l'image Ubuntu la plus récente
FROM ubuntu:latest

# Mettre à jour la liste des paquets et upgrader
RUN apt-get update && apt-get upgrade -y

# Commande exécutée quand on lance le conteneur
CMD ["echo", "Hello, World!"]
